name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # If you need to build your site (not needed for static HTML)
      # - name: Build site
      #   run: npm install && npm run build
